import { useCallback, useEffect, useState } from 'react';

type Collection = {
  marketplace: 'opensea' | 'magiceden';
    slug?: string;
      symbol?: string;
        name: string;
          imageUrl?: string | null;
            royaltiesEnabled: boolean;
              floorPrice: number | null;
                volumeTotal: number | null;
                  error?: string;
                  };

                  type LinkedCollection = {
                    marketplace: string;
                      collectionKey: string;
                        contractId: string;
                          linkedAt: string;
                          };

                          const REFRESH_MS = 30_000;

                          function collectionKeyOf(c: Collection): string {
                            return c.marketplace === 'opensea' ? (c.slug ?? '') : (c.symbol ?? '');
                            }

                            export default function MarketplaceIntegration() {
                              const [walletAddress, setWalletAddress] = useState('');
                                const [chain, setChain] = useState<'ethereum' | 'solana'>('ethereum');
                                  const [discovered, setDiscovered] = useState<Collection[]>([]);
                                    const [linked, setLinked] = useState<LinkedCollection[]>([]);
                                      const [loading, setLoading] = useState(false);
                                        const [error, setError] = useState<string | null>(null);

                                          const loadLinked = useCallback(async () => {
                                              try {
                                                    const res = await fetch('/api/v1/marketplaces/linked');
                                                          if (!res.ok) throw new Error(`Failed to load linked collections (${res.status})`);
                                                                const data = await res.json();
                                                                      setLinked(data.collections ?? []);
                                                                          } catch (err) {
                                                                                setError((err as Error).message);
                                                                                    }
                                                                                      }, []);

                                                                                        useEffect(() => {
                                                                                            loadLinked();
                                                                                                const id = setInterval(loadLinked, REFRESH_MS);
                                                                                                    return () => clearInterval(id);
                                                                                                      }, [loadLinked]);

                                                                                                        async function handleDiscover() {
                                                                                                            setLoading(true);
                                                                                                                setError(null);
                                                                                                                    try {
                                                                                                                          const res = await fetch('/api/v1/marketplaces/discover', {
                                                                                                                                  method: 'POST',
                                                                                                                                          headers: { 'Content-Type': 'application/json' },
                                                                                                                                                  body: JSON.stringify({ walletAddress, chain }),
                                                                                                                                                        });
                                                                                                                                                              if (!res.ok) throw new Error(`Discovery failed (${res.status})`);
                                                                                                                                                                    const data = await res.json();
                                                                                                                                                                          setDiscovered(data.collections ?? []);
                                                                                                                                                                              } catch (err) {
                                                                                                                                                                                    setError((err as Error).message);
                                                                                                                                                                                        } finally {
                                                                                                                                                                                              setLoading(false);
                                                                                                                                                                                                  }
                                                                                                                                                                                                    }

                                                                                                                                                                                                      async function handleLink(collection: Collection, contractId: string) {
                                                                                                                                                                                                          try {
                                                                                                                                                                                                                const res = await fetch('/api/v1/marketplaces/link', {
                                                                                                                                                                                                                        method: 'POST',
                                                                                                                                                                                                                                headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                        body: JSON.stringify({
                                                                                                                                                                                                                                                  marketplace: collection.marketplace,
                                                                                                                                                                                                                                                            collectionKey: collectionKeyOf(collection),
                                                                                                                                                                                                                                                                      contractId,
                                                                                                                                                                                                                                                                              }),
                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                          if (!res.ok) throw new Error(`Link failed (${res.status})`);
                                                                                                                                                                                                                                                                                                await loadLinked();
                                                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                                                          setError((err as Error).message);
                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                  async function handleUnlink(entry: LinkedCollection) {
                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                            const res = await fetch('/api/v1/marketplaces/unlink', {
                                                                                                                                                                                                                                                                                                                                    method: 'POST',
                                                                                                                                                                                                                                                                                                                                            headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                    body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                              marketplace: entry.marketplace,
                                                                                                                                                                                                                                                                                                                                                                        collectionKey: entry.collectionKey,
                                                                                                                                                                                                                                                                                                                                                                                }),
                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                            if (!res.ok) throw new Error(`Unlink failed (${res.status})`);
                                                                                                                                                                                                                                                                                                                                                                                                  await loadLinked();
                                                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                            setError((err as Error).message);
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                        <section aria-labelledby="marketplace-integration-heading">
                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 id="marketplace-integration-heading">Marketplace Integration</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <label htmlFor="wallet-address">Wallet address</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                              id="wallet-address"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={walletAddress}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setWalletAddress(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="0x... or Solana address"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label htmlFor="chain-select">Chain</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              id="chain-select"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={chain}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setChain(e.target.value as 'ethereum' | 'solana')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="ethereum">Ethereum (OpenSea)</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="solana">Solana (Magic Eden)</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={handleDiscover} disabled={loading || !walletAddress}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {loading ? 'Scanning…' : 'Discover collections'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {error && <p role="alert">{error}</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {discovered.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3>Discovered collections</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {discovered.map((c) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li key={`${c.marketplace}:${collectionKeyOf(c)}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <strong>{c.name}</strong> ({c.marketplace})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {c.royaltiesEnabled ? ' — royalties enabled' : ' — no royalties'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {c.floorPrice != null && <> · floor {c.floorPrice}</>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {c.royaltiesEnabled && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const contractId = window.prompt('SRS contract ID to link:');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (contractId) handleLink(c, contractId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Link to contract
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h3>Connected collections</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {linked.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>No collections linked yet.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {linked.map((entry) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <li key={`${entry.marketplace}:${entry.collectionKey}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {entry.collectionKey} ({entry.marketplace}) → contract {entry.contractId}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={() => handleUnlink(entry)}>Disconnect</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }